FROM nginx:1.23-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./nginxconfig.io/general.conf /etc/nginx/nginxconfig.io/general.conf
COPY ./nginxconfig.io/proxy.conf /etc/nginx/nginxconfig.io/proxy.conf
