spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/country_info_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: 8091
